### ISSUE TITLE
Exception, not working

### ISSUE THREAD

**Issue by ronenfe** [jrummyapps/colorpicker#116]
<com.jaredrummler.android.colorpicker.ColorPreferenceCompat
            app:defaultValue="#FF9999"
            app:key="day_speed_color_picker1"
            app:summary="Choose your color"
            app:title="Dial color for day theme"/>

autovolumefree         E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: net.festinger.autovolumefree, PID: 14580
                                                                                                    android.view.InflateException: Binary XML file line #19: Error inflating class com.jaredrummler.android.colorpicker.ColorPreferenceCompat
                                                                                                    	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:253)
                                                                                                    	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281)
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349)
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351)
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
                                                                                                    	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380)
                                                                                                    	at net.festinger.autovolumefree.SettingsFragment.onCreatePreferences(SettingsFragment.kt:58)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:246)
                                                                                                    	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112) 
                                                                                                    	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380) 
                                                                                                    	at net.festinger.autovolumefree.SettingsFragment.onCreatePreferences(SettingsFragment.kt:58) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278) 
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189) 
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100) 
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002) 
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 18 to integer: type=0x3, theme={InheritanceMap=[id=0x7f120163net.festinger.autovolumefree:style/PreferenceThemeOverlay, id=0x7f12011fnet.festinger.autovolumefree:style/BasePreferenceThemeOverlay], Themes=[net.festinger.autovolumefree:style/PreferenceThemeOverlay, not forced, net.festinger.autovolumefree:style/Theme.AutoVolume, forced, net.festinger.autovolumefree:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                                                                                                    	at android.content.res.TypedArray.getInteger(TypedArray.java:652)
                                                                                                    	at com.jaredrummler.android.colorpicker.ColorPreferenceCompat.onGetDefaultValue(ColorPreferenceCompat.java:142)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:255)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:299)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:314)
                                                                                                    	at com.jaredrummler.android.colorpicker.ColorPreferenceCompat.<init>(ColorPreferenceCompat.java:36)
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                                                                                                    	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:246) 
                                                                                                    	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112) 
                                                                                                    	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380) 
                                                                                                    	at net.festinger.autovolumefree.SettingsFragment.onCreatePreferences(SettingsFragment.kt:58) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278) 
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189) 
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100) 
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002) 
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

**Comment by ronenfe** [comment]
It's because it can't accept a string color I think, only int.

**Comment by ronenfe** [comment]
The problem is you must provide it in this format 0xFF9999 otherwise it will throw exception, although the preview will work. Impossible to debug it. I found it out by trial and error. Also no autocompletion in the xml for the custom attributes.

**Comment by ronenfe** [comment]
Seems it only works on Android 15, on lower versions i get this: 
![Screenshot_20241116_213029](https://github.com/user-attachments/assets/44bd4d3d-aaed-433f-9787-308dca48a547)

**Comment by ronenfe** [comment]
I had to add             app:cpv_showAlphaSlider="true"
and move the slider to 0 because it has a default of 100%. But i don't want the users to have to do that.

**Comment by ronenfe** [comment]
ok it works now, i'm not sure what was the problem.

**Comment by Toni500github** [comment]
could you help me too? I want to use this library because a color picker in preferences is hella cool, though I only get exceptions
for example
```xml
        <com.jaredrummler.android.colorpicker.ColorPreferenceCompat
            android:title="Default custom color"
            android:key="default_custom_color"
            app:useSimpleSummaryProvider="true"
            app:cpv_showAlphaSlider="true" />
```
Will still throw because of `java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer`
caused by
```java
@Override protected void onSetInitialValue(Object defaultValue) {
    super.onSetInitialValue(defaultValue);
    if (defaultValue instanceof Integer) {
      color = (Integer) defaultValue;
      persistInt(color);
    } else {
      color = getPersistedInt(0xFF000000); // here
    }
  }
```

Uh?

**Comment by ronenfe** [comment]
I wrote there the answer: The problem is you must provide it in this format 0xFF9999 otherwise it will throw exception, although the preview will work. Impossible to debug it. I found it out by trial and error. Also no autocompletion in the xml for the custom attributes.

**Comment by Toni500github** [comment]
> The problem is you must provide it in this format 0xFF9999 otherwise it will throw exception

```xml
<com.jaredrummler.android.colorpicker.ColorPreferenceCompat
            app:key="default_custom_color"
            app:title="Default custom color"
            app:defaultValue="0xFF9999"
            android:enabled="false"
            app:useSimpleSummaryProvider="true" />
```
throws `java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer`
if I then change `0x` to `#` it throws
```
android.view.InflateException: Binary XML file line #36: Error inflating class com.jaredrummler.android.colorpicker.ColorPreferenceCompat
                                                                                                    	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:253)
                                                                                                    	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281)
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349)
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351)
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161)
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112)
                                                                                                    	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380)
                                                                                                    	at org.toni.customfetch_android.SettingsFragment.onCreatePreferences(SettingsFragment.kt:50)
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161)
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at androidx.preference.PreferenceInflater.createItem(PreferenceInflater.java:246)
                                                                                                    	at androidx.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:281) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:349) 
                                                                                                    	at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:351) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:161) 
                                                                                                    	at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:112) 
                                                                                                    	at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:217) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:380) 
                                                                                                    	at org.toni.customfetch_android.SettingsFragment.onCreatePreferences(SettingsFragment.kt:50) 
                                                                                                    	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:161) 
                                                                                                    	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268) 
                                                                                                    	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943) 
                                                                                                    	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839) 
                                                                                                    	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782) 
                                                                                                    	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232) 
                                                                                                    	at android.os.Looper.loop(Looper.java:317) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8705) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886) 
                                                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 11 to integer: type=0x3, theme={InheritanceMap=[id=0x7f110164org.toni.customfetch_android:style/PrefsTheme, id=0x7f110163org.toni.customfetch_android:style/PreferenceThemeOverlay.v14.Material, id=0x7f110162org.toni.customfetch_android:style/PreferenceThemeOverlay.v14, id=0x7f110161org.toni.customfetch_android:style/PreferenceThemeOverlay, id=0x7f11011forg.toni.customfetch_android:style/BasePreferenceThemeOverlay], Themes=[org.toni.customfetch_android:style/PrefsTheme, not forced, org.toni.customfetch_android:style/Theme.MainActivity, forced, org.toni.customfetch_android:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
                                                                                                    	at android.content.res.TypedArray.getInteger(TypedArray.java:652)
                                                                                                    	at com.jaredrummler.android.colorpicker.ColorPreferenceCompat.onGetDefaultValue(ColorPreferenceCompat.java:142)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:257)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:299)
                                                                                                    	at androidx.preference.Preference.<init>(Preference.java:314)
                                                                                                    	at com.jaredrummler.android.colorpicker.ColorPreferenceCompat.<init>(ColorPreferenceCompat.java:36)
```
caused at
```java
  @Override protected Object onGetDefaultValue(TypedArray a, int index) {
    return a.getInteger(index, Color.BLACK);
  }
```

**Comment by ronenfe** [comment]
<com.jaredrummler.android.colorpicker.ColorPreferenceCompat
            app:key="theme_color"
            app:icon="@drawable/baseline_diamond_24"
            app:summary="Color theme"
            app:enabled="false"
            app:title="Change color theme"/>

I set the color in the code, I don't remember how I wrote it in the xml.

**Comment by ronenfe** [comment]
themeColor?.saveValue(sharedPreferences.getInt(themeColor?.key,getPrimaryColor(requireContext())))
aga
fun getPrimaryColor(context: Context): Int {
        val typedValue = TypedValue()
        context.theme.resolveAttribute(com.google.android.material.R.attr.colorPrimary, typedValue, true)
        return typedValue.data
    }

This is what I do to set it to the primary color of the current theme. You can use it and debug to see the correct format. You have to give it int. But I don't remember how I did it in the xml anymore. You can see the int value and try to figure out. I'm pretty sure what I wrote here previously worked. I can try it later.

**Comment by Toni500github** [comment]
```kotlin
    override fun onCreatePreferences(savedInstanceState: Bundle?, rootKey: String?) {
        setPreferencesFromResource(R.xml.root_preferences, rootKey)

        val defaultCustomColor = findPreference<ColorPreferenceCompat>("default_custom_color")

        val defaultBgColor = findPreference<ListPreference>("default_bg_color")
        defaultCustomColor?.isEnabled = (defaultBgColor?.findIndexOfValue(defaultBgColor.value.toString()) == 2)
        defaultBgColor?.setOnPreferenceChangeListener { _, newValue ->
            defaultCustomColor?.isEnabled = (defaultBgColor.findIndexOfValue(newValue.toString()) == 2)
            true
        }
    }
```
the program segfaults everytime when calling `setPreferencesFromResource(R.xml.root_preferences, rootKey) `, with or without setting `android:defaultValue` in xml.

As you can see in the stacktrace, it mentions `at org.toni.customfetch_android.SettingsFragment.onCreatePreferences(SettingsFragment.kt:50)` which is the exact line of the function call

**Comment by ronenfe** [comment]
I think i know what's your problem. you need to clear storage because it loads automatically the value you set before in shared pref, you may store a bad value. Also I found out how to make it opaque. Use a default value  starting with FF
example: app:defaultValue="0xFFFF9999"

![Image](https://github.com/user-attachments/assets/49678439-735a-4f65-bca3-009a78bfa48a)

**Comment by Toni500github** [comment]
YES, that was the issue. cleared storage and now it works. Thanks!
