### ISSUE TITLE
Crash when initial color is 0

### ISSUE THREAD

**Issue by hyb1996** [jrummyapps/colorpicker#9]
Version:
2.1.5
Code:
ColorPickerDialog dialog = ColorPickerDialog.newBuilder()
                    .setAllowCustom(true)
                    .setAllowPresets(false)
                    .setDialogType(ColorPickerDialog.TYPE_CUSTOM)
                    .setShowAlphaSlider(false)
                    .setDialogTitle(R.string.text_select_color)
                    //HERE! set initial color to 0
                    .setColor(0)
                    .create();
Log:
java.lang.StringIndexOutOfBoundsException: length=1; index=2
                                                                             at java.lang.String.substring(String.java:1897)
                                                                             at com.jrummyapps.android.colorpicker.ColorPickerDialog.setHex(ColorPickerDialog.java:354)
                                                                             at com.jrummyapps.android.colorpicker.ColorPickerDialog.createPickerView(ColorPickerDialog.java:274)
                                                                             at com.jrummyapps.android.colorpicker.ColorPickerDialog.onCreateDialog(ColorPickerDialog.java:163)
                                                                             at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:406)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
                                                                             at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                             at android.app.BackStackRecord.run(BackStackRecord.java:815)
                                                                             at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
                                                                             at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                                                                             at android.os.Handler.handleCallback(Handler.java:751)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jaredrummler** [comment]
If you aren't using the alpha slider you most likely don't want the default color to have an alpha channel. Use 0xFF000000 instead of 0.
