### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by qijaz221** [jrummyapps/colorpicker#95]
Getting few instances of NumberFormatException reported through Firebase, here's the full stack-trace:

```
Fatal Exception: java.lang.NumberFormatException: Invalid int: "te"
       at java.lang.Integer.invalidInt(Integer.java:138)
       at java.lang.Integer.parse(Integer.java:410)
       at java.lang.Integer.parseInt(Integer.java:367)
       at com.jrummyapps.android.colorpicker.ColorPickerDialog.parseColorString(ColorPickerDialog.java:378)
       at com.jrummyapps.android.colorpicker.ColorPickerDialog.afterTextChanged(ColorPickerDialog.java:341)
       at android.widget.TextView.sendAfterTextChanged(TextView.java:8004)
       at android.widget.TextView.setText(TextView.java:4356)
       at android.widget.TextView.setText(TextView.java:4204)
       at android.widget.EditText.setText(EditText.java:84)
       at android.widget.TextView.setText(TextView.java:4179)
       at android.widget.EditText.performAccessibilityActionInternal(EditText.java:136)
       at android.view.View.performAccessibilityAction(View.java:8889)
       at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668)
       at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Last reported from:
Device: Nexus 5X
Android: 6.0.1

Tried an emulator but couldn't reproduce it as entering `te` in custom mode only registers `e` so not sure how someone managed to input an invalid string.

**Comment by 00ec454** [comment]
@jaredrummler  I'm having the same issue exactly from same device and same android version. If you can advise, I can open PR for fix

**Comment by qijaz221** [comment]
A bit more information regarding this, after I submitted a recent update for review on Play Store with 'Managed Publishing' turned on, I got a crash report from same device/Android version without actually having the update 'Published'.

This leads me to believe it is Google's automated testing that somehow manages to enter `te` but still not sure how.
